services:
  - type: web
    name: discord-music-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python discord_music_bot.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
    disk:
      name: bot-disk
      mountPath: /opt/render/project/src
      sizeGB: 1