services:
  - type: web
    name: discord-music-bot
    env: python
    plan: free
    buildCommand: pip install discord.py==2.3.2 yt-dlp==2023.12.30 spotipy==2.24.0 opuslib==3.0.1 PyNaCl==1.5.0
    startCommand: python discord_music_bot.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false